[package]
name = "rusty_secrets"
version = "0.0.1"
description = "Implementation of threshold Shamir secret sharing in the Rust programming language." 
license = "GPLv3"
readme = "README.md"

[dependencies]
getopts = "^0.2.14"
rustc-serialize = "^0.3.18"
rand = "^0.3.14"

[lib]
name = "rusty_secrets"
path = "src/lib/mod.rs"
crate_type = ["rlib"]

[[bin]]
name = "rusty_secrets_bin"
path = "src/main.rs"
