[package]
name = "secretshare"
version = "0.1.3"
authors = ["Sebastian Gesemann <s.gesemann@gmail.com>"]
description = "This is an implementation of Shamir's secret sharing scheme."
license = "GPLv3"
readme = "README.md"

[dependencies]
getopts = "^0.2.1"
rustc-serialize = "^0.2.11"
crc24 = "^0.1.0"
rand = "^0.1.2"
